name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  init:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{matrix.node-version}}
      - name: Install modules
        run: npm install
        working-directory: frontend
      - name: Build project
        run: npm run dev
        working-directory: frontend
